CALL makezone.bat zone1 hotwater
CALL makezone.bat zone2 dining
CALL makezone.bat zone3 office
CALL makezone.bat zone4 hall
CALL makezone.bat zone5 sittingroom
CALL makezone.bat zone6 gardenroom
CALL makezone.bat zone7 upbath
CALL makezone.bat zone8 ensuite
CALL makezone.bat zone9 gndbath
CALL makezone.bat zone10 playroom
CALL makezone.bat zone11 kitchen
CALL makezone.bat zone12 masterbed
CALL makezone.bat zone13 landing
CALL makezone.bat zone14 guestbed
CALL makezone.bat zone15 notused
CALL makezone.bat zone16 kidsrooms
